---
# tasks file for tomcat8
# - name: checkout latest TC release
#   git:
#     repo: ssh://git@github.com:repo.git
#     dest: /usr/local/tomcat-admin
#     accept_hostkey: true

# # alternatively copy from local dir in files/
# - name: copy TC-Admin distribution
#   copy:
#     force=no
#     src=tomcat-admin/tomcat8/
#     dest=/usr/local/tomcat-admin

- debug: msg="setup of instance <{{ loop_item['name'] }}>"
- name: create Tomcat group
  group:
    name: tomcat
    state: present

- name: create Tomcat user
  user:
    name: tomcat
    state: present
    comment: "Tomcat runtime user"
    group: tomcat



### single instance defined in var: 'tomcat_instance'
- name: check if instance exists
  stat:
    path: /opt/tomcat/{{ loop_item['name'] }}
  register: tc_exists


- debug:
    msg: "Instance {{ loop_item['name'] }} exists"
  when: tc_exists.stat.isdir is defined and tc_exists.stat.isdir


- name: create tomcat instance
  command: /bin/bash /usr/local/tomcat-admin/tc.sh -n {{ loop_item['name'] }} --offset={{ loop_item['offset'] }}
  when: tc_exists.stat.isdir is undefined
  register: command_result

- name: show Command result
  debug:
    msg: "{{ command_result }} "
  when: tc_exists.stat.isdir is undefined
