---

# tasks file for tomcat8
# - name: checkout latest TC release
#   git:
#     repo: ssh://git@github.com:repo.git
#     dest: /usr/local/tomcat-admin
#     accept_hostkey: true

- name: create script directory
  file:
    name: /usr/local/tomcat-admin
    state: directory

# copy from local dir in files/
- name: deploy TC-Admin script
  unarchive:
    src:  tomcat-admin/tomcat8.tar
    dest: /usr/local/tomcat-admin
    owner: root
    group: root
    list_files: true


# - include: single.yml
- include: multi.yml
# - include: loop_control.yml

- include: deployApps.yml
