---

- name: create app dir
  file:
    name: /opt/tomcat/{{ item.0.name }}/{{ item.1.dir }}/{{ item.1.appName }}
    state: directory
  with_nested:
    -  "{{ tomcat_instances }}"
    -  [ { file: "probe24.war.zip", appName: "probe24", dir: "adminapps" }, { file: "jolokia.war", appName: "jolokia", dir: "adminapps" }]

- name: install unzip as required by module unarchive
  zypper:
    name: unzip
    state: present

- name: deploy applications
  unarchive:
    src: apps/{{ item.1.file }}
    dest: /opt/tomcat/{{ item.0.name }}/{{ item.1.dir }}/{{ item.1.appName }}

  with_nested:
    -  "{{ tomcat_instances }}"
    -  [ { file: "probe24.war.zip", appName: "probe24", dir: "adminapps" }, { file: "jolokia.war", appName: "jolokia", dir: "adminapps" }]
  register: command_result

